version: "3.8"

services:
  db:
    image: mysql:8.4
    container_name: holamundo-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: holamundo
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - holamundo-net

  app:
    build: ./app
    container_name: holamundo-app
    depends_on:
      - db
    networks:
      - holamundo-net

  nginx:
    image: nginx:alpine
    container_name: holamundo-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - holamundo-net

networks:
  holamundo-net:
    driver: bridge

