version: '3.8'

services:
  db:
    image: mysql:8
    container_name: holamundo-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: holamundo
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: ./app
    container_name: holamundo-app
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: holamundo

